# Generated by Django 3.2 on 2021-07-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myaccounts', '0002_remove_myuser_passusr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccounts.myuser')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
