# Generated by Django 3.2 on 2021-07-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
