# Generated by Django 3.2 on 2021-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_personne_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_entr',
            field=models.DateField(null=True),
        ),
    ]
