# Generated by Django 3.2 on 2021-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_personne_date_entr'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='year_prod',
            field=models.IntegerField(null=True),
        ),
    ]
