# Generated by Django 3.2 on 2021-07-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210727_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personne',
            options={'ordering': ['id']},
        ),
    ]
